#!/bin/bash

# Define the arguments list
args=("pig_latin" "saddle_points" "circular_buffer" "custom_set" "twelve_days" "rna_transcription" "crypto_square" "accumulate" "killer_sudoku_helper" "gigasecond" "react" "raindrops" "transpose" "resistor_color_expert" "error_handling" "variable_length_quantity" "rational_numbers" "affine_cipher" "triangle" "book_store" "satellite" "point_mutations" "two_fer" "tree_building" "go_counting" "bowling" "queen_attack" "markdown" "phone_number" "bob" "word_count" "all_your_base" "darts" "flatten_array" "zipper" "diamond" "knapsack" "say" "beer_song" "house" "hello_world" "food_chain" "alphametics" "proverb" "forth" "minesweeper" "matrix" "robot_name" "resistor_color_duo" "robot_simulator" "binary" "secret_handshake" "paasio" "square_root" "reverse_string" "hangman" "acronym" "binary_search_tree" "high_scores" "grade_school" "poker" "nth_prime" "difference_of_squares" "ledger" "clock" "yacht" "sublist" "dnd_character" "hexadecimal" "etl" "bottle_song" "resistor_color_trio" "complex_numbers" "grep" "linked_list" "palindrome_products" "dot_dsl" "dominoes" "sum_of_multiples" "octal" "change" "eliuds_eggs" "rail_fence_cipher" "strain" "diffie_hellman" "pascals_triangle" "matching_brackets" "anagram" "pangram" "scale_generator" "list_ops" "allergies" "isogram" "run_length_encoding" "protein_translation" "resistor_color" "perfect_numbers" "roman_numerals" "pov" "scrabble_score" "ocr_numbers" "zebra_puzzle" "armstrong_numbers" "rotational_cipher" "tournament" "atbash_cipher" "rest_api" "connect" "prime_factors" "trinary" "grains" "spiral_matrix" "binary_search" "wordy" "largest_series_product" "sgf_parsing" "collatz_conjecture" "sieve" "hamming" "series" "bank_account" "isbn_verifier" "luhn" "pythagorean_triplet" "simple_linked_list" "leap" "space_age" "kindergarten_garden" "simple_cipher" "meetup" "word_search" "rectangles" "two_bucket")
# Convert the array to a single string of space-separated values
for arg in "${args[@]}"; do
    python scripts/run.py scripts/config_aider.yaml --agent zero_shot --uuid $1 -p "zero_shot.problems=[$arg]"
done


