# Jekyll Configuration
title: "MSR Montreal Froggy Team"
description: "Building the future of AI-assisted software engineering"
baseurl: "/debug-gym"
url: "https://microsoft.github.io"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  posts:
    output: true
    permalink: /blog/:year/:month/:title/

# Defaults
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "blog-post"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .bundle
  - .sass-cache
  - _site

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
